export function parseArgs(argv) {
  const out = { _: [] };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--json') out.json = true;
    else if (arg === '--fix') out.fix = true;
    else if (arg === '--finalize') out.finalize = true;
    else if (arg === '--version' || arg === '-v') out.version = true;
    else if (arg === '--all') out.all = true;
    else if (arg === '--all-history') out.allHistory = true;
    else if (arg === '--reimport') out.reimport = true;
    else if (arg === '--password-stdin') out.passwordStdin = true;
    else if (arg === '--no-images') out.images = false;
    else if (arg === '--close-tab') out.closeTab = true;
    else if (arg === '--out') out.out = argv[++index];
    else if (arg === '--config') out.config = argv[++index];
    else if (arg === '--state-dir') out.stateDir = argv[++index];
    else if (arg === '--run-id') out.runId = argv[++index];
    else if (arg === '--status') out.status = argv[++index];
    else if (arg === '--input') out.input = argv[++index];
    else if (arg === '--host') out.host = argv[++index];
    else if (arg === '--database') out.database = argv[++index];
    else if (arg === '--reader-user') out.readerUser = argv[++index];
    else if (arg === '--ingest-user') out.ingestUser = argv[++index];
    else if (arg === '--pgpass-file') out.pgpassFile = argv[++index];
    else if (arg === '--credential-file') out.credentialFile = argv[++index];
    else if (arg === '--dataset') out.dataset = argv[++index];
    else if (arg === '--metrics') out.metrics = argv[++index];
    else if (arg === '--group-by') out.groupBy = argv[++index];
    else if (arg === '--order-by') out.orderBy = argv[++index];
    else if (arg === '--limit') out.limit = argv[++index];
    else if (arg === '--asc') out.orderDesc = false;
    else if (arg === '--cache-path') out.cachePath = argv[++index];
    else if (arg === '--cdp-url') out.cdpUrl = argv[++index];
    else if (arg === '--profile-dir') out.profileDir = argv[++index];
    else if (arg === '--chrome-path') out.chromePath = argv[++index];
    else if (arg === '--session-mode') out.sessionMode = argv[++index];
    else if (arg === '--port') out.port = argv[++index];
    else if (arg === '--url') out.url = argv[++index];
    else if (arg === '--trade-id') out.tradeId = argv[++index];
    else if (arg === '--campaign-id') out.campaignId = argv[++index];
    else if (arg === '--report-id') out.reportId = argv[++index];
    else if (arg === '--report-name') out.reportName = argv[++index];
    else if (arg === '--data-platform') out.dataPlatform = argv[++index];
    else if (arg === '--data-type') out.dataType = argv[++index];
    else if (arg === '--data-dimension') out.dataDimension = argv[++index];
    else if (arg === '--date-type') out.dateType = argv[++index];
    else if (arg === '--fields') out.fields = argv[++index];
    else if (arg === '--item-ids') out.itemIds = argv[++index];
    else if (arg === '--device') out.device = argv[++index];
    else if (arg === '--filter') (out.filters ||= []).push(argv[++index]);
    else if (arg === '--agent') out.agent = argv[++index];
    else if (arg === '--target-dir') out.targetDir = argv[++index];
    else if (arg === '--mode') out.mode = argv[++index];
    else if (arg === '--keyword') out.keyword = argv[++index];
    else if (arg === '--start-date') out.startDate = argv[++index];
    else if (arg === '--end-date') out.endDate = argv[++index];
    else if (arg === '--days') out.days = argv[++index];
    else if (arg === '--tid') out.tid = argv[++index];
    else if (arg === '--seller-id') out.sellerId = argv[++index];
    else if (arg === '--shop-id') out.shopId = argv[++index];
    else if (arg === '--max-pages') out.maxPages = argv[++index];
    else if (arg === '--max-depth') out.maxDepth = argv[++index];
    else if (arg === '--page') out.page = argv[++index];
    else if (arg === '--page-size') out.pageSize = argv[++index];
    else if (arg === '--delay-ms') out.delayMs = argv[++index];
    else if (arg === '--min-delay-ms') out.minDelayMs = argv[++index];
    else if (arg === '--max-delay-ms') out.maxDelayMs = argv[++index];
    else if (arg === '--duration-ms') out.durationMs = argv[++index];
    else if (arg === '--timeout-ms') out.timeoutMs = argv[++index];
    else if (arg === '--keep-page') out.keepPage = true;
    else if (arg === '-h' || arg === '--help') out.help = true;
    else out._.push(arg);
  }
  return out;
}
